/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chk.chkui;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author chkp
 */
public class CreateContract extends javax.swing.JDialog {

    /**
     * Creates new form CreateContract
     */
    public CreateContract(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        pasosPanel = new javax.swing.JPanel();
        paso1Panel = new javax.swing.JPanel();
        paso2Panel = new javax.swing.JPanel();
        paso3Panel = new javax.swing.JPanel();
        pasosComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("Create contract");

        pasosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pasosPanel.setLayout(new java.awt.CardLayout(4, 4));

        paso1Panel.setBackground(new java.awt.Color(255, 153, 153));
        paso1Panel.setName("Paso 1"); // NOI18N

        javax.swing.GroupLayout paso1PanelLayout = new javax.swing.GroupLayout(paso1Panel);
        paso1Panel.setLayout(paso1PanelLayout);
        paso1PanelLayout.setHorizontalGroup(
            paso1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        paso1PanelLayout.setVerticalGroup(
            paso1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        pasosPanel.add(paso1Panel, "Paso 1");

        paso2Panel.setBackground(new java.awt.Color(153, 255, 153));
        paso2Panel.setName("Paso 2"); // NOI18N

        javax.swing.GroupLayout paso2PanelLayout = new javax.swing.GroupLayout(paso2Panel);
        paso2Panel.setLayout(paso2PanelLayout);
        paso2PanelLayout.setHorizontalGroup(
            paso2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        paso2PanelLayout.setVerticalGroup(
            paso2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        pasosPanel.add(paso2Panel, "Paso 2");

        paso3Panel.setBackground(new java.awt.Color(153, 153, 255));
        paso3Panel.setName("Paso 3"); // NOI18N

        javax.swing.GroupLayout paso3PanelLayout = new javax.swing.GroupLayout(paso3Panel);
        paso3Panel.setLayout(paso3PanelLayout);
        paso3PanelLayout.setHorizontalGroup(
            paso3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        paso3PanelLayout.setVerticalGroup(
            paso3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        pasosPanel.add(paso3Panel, "Paso 3");

        // pasosNames
        pasosNames = new ArrayList<>();
        int pasosCount = 0;
        for(Component c : pasosPanel.getComponents()) {
            if (c instanceof javax.swing.JPanel) {
                pasosCount++;
                pasosNames.add(c.getName());
            }
        }

        pasosComboBox.setModel(new DefaultComboBoxModel(pasosNames.toArray()));
        pasosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pasosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pasosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pasosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pasosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasosComboBoxActionPerformed
        int selectedIndex = pasosComboBox.getSelectedIndex(); 
        if (selectedIndex == -1) { return; }
        
        String targetName = pasosNames.get(selectedIndex);
        
        CardLayout layout = (CardLayout)(pasosPanel.getLayout());
        layout.show(pasosPanel, targetName);
    }//GEN-LAST:event_pasosComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel paso1Panel;
    private javax.swing.JPanel paso2Panel;
    private javax.swing.JPanel paso3Panel;
    private javax.swing.JComboBox<String> pasosComboBox;
    private javax.swing.JPanel pasosPanel;
    private List<String> pasosNames;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
