/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chk.chkui;

import gobierno.Reparticion;
import gobierno.Trabajador;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author chkp
 */
public class EnumerateUsers extends javax.swing.JFrame {

    /**
     * Creates new form EnumerateUsers
     * @param gobierno
     */
    public EnumerateUsers(gobierno.Gobierno gobierno) {
        initComponents();
        setGobierno(gobierno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gobierno = new gobierno.Gobierno();
        splitPanel = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        reparticionTitle = new javax.swing.JLabel();
        reparticionScrollPane = new javax.swing.JScrollPane();
        reparticionTree = new javax.swing.JTree();
        leftButtonsPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        trabajadoresScrollPane = new javax.swing.JScrollPane();
        trabajadoresTable = new javax.swing.JTable();
        rightButtonsPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        mainButtonsPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPanel.setDividerLocation(256);

        reparticionTitle.setText("Reparticiones");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        reparticionTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        reparticionTree.setRootVisible(false);
        reparticionTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                reparticionTreeValueChanged(evt);
            }
        });
        reparticionScrollPane.setViewportView(reparticionTree);

        leftButtonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        leftButtonsPanel.setLayout(new java.awt.GridLayout(2, 2, 4, 4));

        jButton3.setText("jButton3");
        leftButtonsPanel.add(jButton3);

        jButton4.setText("jButton4");
        leftButtonsPanel.add(jButton4);

        jButton5.setText("jButton5");
        leftButtonsPanel.add(jButton5);

        jButton6.setText("jButton6");
        leftButtonsPanel.add(jButton6);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reparticionScrollPane)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(reparticionTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(leftButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reparticionTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reparticionScrollPane)
                .addGap(18, 18, 18)
                .addComponent(leftButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPanel.setLeftComponent(leftPanel);

        jLabel2.setText("Trabajadores");

        trabajadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trabajadoresScrollPane.setViewportView(trabajadoresTable);

        rightButtonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        rightButtonsPanel.setLayout(new java.awt.GridLayout(2, 3, 4, 4));

        jButton7.setText("jButton7");
        rightButtonsPanel.add(jButton7);

        jButton8.setText("jButton8");
        rightButtonsPanel.add(jButton8);

        jButton9.setText("jButton9");
        rightButtonsPanel.add(jButton9);

        jButton10.setText("jButton10");
        rightButtonsPanel.add(jButton10);

        jButton11.setText("jButton11");
        rightButtonsPanel.add(jButton11);

        jButton12.setText("jButton12");
        rightButtonsPanel.add(jButton12);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trabajadoresScrollPane)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(rightButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trabajadoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rightButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPanel.setRightComponent(rightPanel);

        jButton1.setText("Volver atras");

        jButton2.setText("Ayuda");

        javax.swing.GroupLayout mainButtonsPanelLayout = new javax.swing.GroupLayout(mainButtonsPanel);
        mainButtonsPanel.setLayout(mainButtonsPanelLayout);
        mainButtonsPanelLayout.setHorizontalGroup(
            mainButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        mainButtonsPanelLayout.setVerticalGroup(
            mainButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainButtonsPanelLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(mainButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reparticionTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_reparticionTreeValueChanged
        // Get the selected item name
        DefaultMutableTreeNode selectedNode =
                (DefaultMutableTreeNode)reparticionTree.getLastSelectedPathComponent();
        Reparticion r = (Reparticion)selectedNode.getUserObject();
        System.out.println("R: " + r.getNombre());
        
        DefaultTableModel tableModel = (DefaultTableModel)trabajadoresTable.getModel();
        tableModel.setRowCount(0);
        
        for (Trabajador t : gobierno.getTrabajadoresEnReparticion(r.getId())) {
            System.out.println("\tT: " + t.getNombre());
            tableModel.addRow(new Object[]{ t.getNombre(), t.getApellido(), t.getFechaDeNacimientoAsString() });
        }
    }//GEN-LAST:event_reparticionTreeValueChanged

    public void setGobierno(gobierno.Gobierno gobierno) {
        this.gobierno = gobierno;
        reloadGobierno();
    }
    
    public void reloadGobierno() {
        DefaultMutableTreeNode treeRoot = new DefaultMutableTreeNode();
        // populate the nodes
        DefaultMutableTreeNode reparticionNode = null;
        for(Reparticion reparticion : gobierno.getReparticiones()){
            reparticionNode = new DefaultMutableTreeNode(reparticion.getNombre());
            reparticionNode.setUserObject(reparticion);
            treeRoot.add(reparticionNode);
        }
        
        DefaultTreeModel treeModel = new DefaultTreeModel(treeRoot);
        this.reparticionTree.setModel(treeModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gobierno.Gobierno gobierno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftButtonsPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainButtonsPanel;
    private javax.swing.JScrollPane reparticionScrollPane;
    private javax.swing.JLabel reparticionTitle;
    private javax.swing.JTree reparticionTree;
    private javax.swing.JPanel rightButtonsPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JScrollPane trabajadoresScrollPane;
    private javax.swing.JTable trabajadoresTable;
    // End of variables declaration//GEN-END:variables
}
