/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chk.chkui;

/**
 *
 * @author chkp
 */
public class LoginAndRegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginAndRegisterForm
     */
    public LoginAndRegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        LoginPanel = new javax.swing.JPanel();
        LoginTitlePanel = new javax.swing.JPanel();
        LoginTitleLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LoginContentsPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        LoginUserLabel = new javax.swing.JLabel();
        LoginUserText = new javax.swing.JTextField();
        LoginPassLabel = new javax.swing.JLabel();
        LoginPassText = new javax.swing.JPasswordField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator3 = new javax.swing.JSeparator();
        LoginButtonsPanel = new javax.swing.JPanel();
        LoginClearButton = new javax.swing.JButton();
        LoginSubmitButton = new javax.swing.JButton();
        RegisterPanel = new javax.swing.JPanel();
        RegisterTitlePanel = new javax.swing.JPanel();
        RegisterTitleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        RegContentsPanel = new javax.swing.JPanel();
        RegUserLabel = new javax.swing.JLabel();
        RegUserText = new javax.swing.JTextField();
        RegEmail1Label = new javax.swing.JLabel();
        RegEmail1Text = new javax.swing.JTextField();
        RegEmail2Label = new javax.swing.JLabel();
        RegEmail2Text = new javax.swing.JTextField();
        RegPass1Label = new javax.swing.JLabel();
        RegPass1Text = new javax.swing.JPasswordField();
        RegPass2Label = new javax.swing.JLabel();
        RegPass2Text = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        RegButtonsPanel = new javax.swing.JPanel();
        RegClearButton = new javax.swing.JButton();
        RegSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginTitlePanel.setLayout(new java.awt.BorderLayout());

        LoginTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LoginTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTitleLabel.setText("Welcome to ChkTest");
        LoginTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginTitlePanel.add(LoginTitleLabel, java.awt.BorderLayout.CENTER);

        LoginContentsPanel.setLayout(new java.awt.GridLayout(4, 2, 4, 4));
        LoginContentsPanel.add(filler1);
        LoginContentsPanel.add(filler2);

        LoginUserLabel.setText("Username");
        LoginContentsPanel.add(LoginUserLabel);
        LoginContentsPanel.add(LoginUserText);
        LoginUserText.getAccessibleContext().setAccessibleName("Login Username Field");
        LoginUserText.getAccessibleContext().setAccessibleDescription("Login Username Field");

        LoginPassLabel.setText("Password");
        LoginContentsPanel.add(LoginPassLabel);

        LoginPassText.setText("jPasswordField1");
        LoginContentsPanel.add(LoginPassText);
        LoginPassText.getAccessibleContext().setAccessibleName("Login Password Field");
        LoginPassText.getAccessibleContext().setAccessibleDescription("Login Password Field");

        LoginContentsPanel.add(filler3);
        LoginContentsPanel.add(filler4);

        LoginButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 4, 4));

        LoginClearButton.setText("Clear");
        LoginButtonsPanel.add(LoginClearButton);

        LoginSubmitButton.setText("Login");
        LoginButtonsPanel.add(LoginSubmitButton);

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addComponent(LoginTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Login", LoginPanel);

        RegisterTitlePanel.setLayout(new java.awt.BorderLayout());

        RegisterTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        RegisterTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterTitleLabel.setText("Welcome to ChkTest");
        RegisterTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterTitlePanel.add(RegisterTitleLabel, java.awt.BorderLayout.CENTER);

        RegContentsPanel.setLayout(new java.awt.GridLayout(5, 2, 4, 4));

        RegUserLabel.setText("Username");
        RegContentsPanel.add(RegUserLabel);

        RegUserText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegContentsPanel.add(RegUserText);
        RegUserText.getAccessibleContext().setAccessibleName("Register Username Field");
        RegUserText.getAccessibleContext().setAccessibleDescription("Register Username Field");

        RegEmail1Label.setText("Email");
        RegContentsPanel.add(RegEmail1Label);

        RegEmail1Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegContentsPanel.add(RegEmail1Text);
        RegEmail1Text.getAccessibleContext().setAccessibleName("Register First Email Field");
        RegEmail1Text.getAccessibleContext().setAccessibleDescription("Register First Email Field");

        RegEmail2Label.setText("Email again");
        RegContentsPanel.add(RegEmail2Label);

        RegEmail2Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegContentsPanel.add(RegEmail2Text);
        RegEmail2Text.getAccessibleContext().setAccessibleName("Register Second Email Field");
        RegEmail2Text.getAccessibleContext().setAccessibleDescription("Register Second Email Field");

        RegPass1Label.setText("Password");
        RegContentsPanel.add(RegPass1Label);

        RegPass1Text.setText("jPasswordField1");
        RegPass1Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegContentsPanel.add(RegPass1Text);
        RegPass1Text.getAccessibleContext().setAccessibleName("Register First Password Field");
        RegPass1Text.getAccessibleContext().setAccessibleDescription("Register First Password Field");

        RegPass2Label.setText("Password again");
        RegContentsPanel.add(RegPass2Label);

        RegPass2Text.setText("jPasswordField1");
        RegPass2Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegContentsPanel.add(RegPass2Text);
        RegPass2Text.getAccessibleContext().setAccessibleName("Register Second Password Field");
        RegPass2Text.getAccessibleContext().setAccessibleDescription("Register Second Password Field");

        RegButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 4, 4));

        RegClearButton.setText("Clear");
        RegButtonsPanel.add(RegClearButton);

        RegSubmitButton.setText("Register");
        RegSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegSubmitButtonActionPerformed(evt);
            }
        });
        RegButtonsPanel.add(RegSubmitButton);

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(RegButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                .addComponent(RegisterTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Register", RegisterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegSubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginButtonsPanel;
    private javax.swing.JButton LoginClearButton;
    private javax.swing.JPanel LoginContentsPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginPassLabel;
    private javax.swing.JPasswordField LoginPassText;
    private javax.swing.JButton LoginSubmitButton;
    private javax.swing.JLabel LoginTitleLabel;
    private javax.swing.JPanel LoginTitlePanel;
    private javax.swing.JLabel LoginUserLabel;
    private javax.swing.JTextField LoginUserText;
    private javax.swing.JPanel RegButtonsPanel;
    private javax.swing.JButton RegClearButton;
    private javax.swing.JPanel RegContentsPanel;
    private javax.swing.JLabel RegEmail1Label;
    private javax.swing.JTextField RegEmail1Text;
    private javax.swing.JLabel RegEmail2Label;
    private javax.swing.JTextField RegEmail2Text;
    private javax.swing.JLabel RegPass1Label;
    private javax.swing.JPasswordField RegPass1Text;
    private javax.swing.JLabel RegPass2Label;
    private javax.swing.JPasswordField RegPass2Text;
    private javax.swing.JButton RegSubmitButton;
    private javax.swing.JLabel RegUserLabel;
    private javax.swing.JTextField RegUserText;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JLabel RegisterTitleLabel;
    private javax.swing.JPanel RegisterTitlePanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
