/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chk.chkui;

/**
 *
 * @author chkp
 */
public class LoginAndRegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginAndRegisterForm
     */
    public LoginAndRegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsPanel = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        loginTitlePanel = new javax.swing.JPanel();
        LoginTitleLabel = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        loginContentsPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginUserLabel = new javax.swing.JLabel();
        loginUserText = new javax.swing.JTextField();
        loginPassLabel = new javax.swing.JLabel();
        loginPassText = new javax.swing.JPasswordField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        separator2 = new javax.swing.JSeparator();
        loginButtonsPanel = new javax.swing.JPanel();
        loginClearButton = new javax.swing.JButton();
        loginSubmitButton = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        registerTitlePanel = new javax.swing.JPanel();
        registerTitleLabel = new javax.swing.JLabel();
        separator3 = new javax.swing.JSeparator();
        registerContentsPanel = new javax.swing.JPanel();
        registerUserLabel = new javax.swing.JLabel();
        registerUserText = new javax.swing.JTextField();
        registerEmail1Label = new javax.swing.JLabel();
        registerEmail1Text = new javax.swing.JTextField();
        registerEmail2Label = new javax.swing.JLabel();
        registerEmail2Text = new javax.swing.JTextField();
        registerPass1Label = new javax.swing.JLabel();
        registerPass1Text = new javax.swing.JPasswordField();
        registerPass2Label = new javax.swing.JLabel();
        registerPass2Text = new javax.swing.JPasswordField();
        separator4 = new javax.swing.JSeparator();
        registerButtonsPanel = new javax.swing.JPanel();
        registerClearButton = new javax.swing.JButton();
        registerSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginTitlePanel.setLayout(new java.awt.BorderLayout());

        LoginTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LoginTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTitleLabel.setText("Welcome to ChkTest");
        LoginTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginTitlePanel.add(LoginTitleLabel, java.awt.BorderLayout.CENTER);

        loginContentsPanel.setLayout(new java.awt.GridLayout(4, 2, 4, 4));
        loginContentsPanel.add(filler1);
        loginContentsPanel.add(filler2);

        loginUserLabel.setText("Username");
        loginContentsPanel.add(loginUserLabel);
        loginContentsPanel.add(loginUserText);
        loginUserText.getAccessibleContext().setAccessibleName("Login Username Field");
        loginUserText.getAccessibleContext().setAccessibleDescription("Login Username Field");

        loginPassLabel.setText("Password");
        loginContentsPanel.add(loginPassLabel);

        loginPassText.setText("jPasswordField1");
        loginContentsPanel.add(loginPassText);
        loginPassText.getAccessibleContext().setAccessibleName("Login Password Field");
        loginPassText.getAccessibleContext().setAccessibleDescription("Login Password Field");

        loginContentsPanel.add(filler3);
        loginContentsPanel.add(filler4);

        loginButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 4, 4));

        loginClearButton.setText("Clear");
        loginButtonsPanel.add(loginClearButton);

        loginSubmitButton.setText("Login");
        loginButtonsPanel.add(loginSubmitButton);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(separator1)
            .addComponent(separator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addComponent(loginTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabsPanel.addTab("Login", loginPanel);

        registerTitlePanel.setLayout(new java.awt.BorderLayout());

        registerTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        registerTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerTitleLabel.setText("Welcome to ChkTest");
        registerTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerTitlePanel.add(registerTitleLabel, java.awt.BorderLayout.CENTER);

        registerContentsPanel.setLayout(new java.awt.GridLayout(5, 2, 4, 4));

        registerUserLabel.setText("Username");
        registerContentsPanel.add(registerUserLabel);

        registerUserText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        registerContentsPanel.add(registerUserText);
        registerUserText.getAccessibleContext().setAccessibleName("Register Username Field");
        registerUserText.getAccessibleContext().setAccessibleDescription("Register Username Field");

        registerEmail1Label.setText("Email");
        registerContentsPanel.add(registerEmail1Label);

        registerEmail1Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        registerContentsPanel.add(registerEmail1Text);
        registerEmail1Text.getAccessibleContext().setAccessibleName("Register First Email Field");
        registerEmail1Text.getAccessibleContext().setAccessibleDescription("Register First Email Field");

        registerEmail2Label.setText("Email again");
        registerContentsPanel.add(registerEmail2Label);

        registerEmail2Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        registerContentsPanel.add(registerEmail2Text);
        registerEmail2Text.getAccessibleContext().setAccessibleName("Register Second Email Field");
        registerEmail2Text.getAccessibleContext().setAccessibleDescription("Register Second Email Field");

        registerPass1Label.setText("Password");
        registerContentsPanel.add(registerPass1Label);

        registerPass1Text.setText("jPasswordField1");
        registerPass1Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        registerContentsPanel.add(registerPass1Text);
        registerPass1Text.getAccessibleContext().setAccessibleName("Register First Password Field");
        registerPass1Text.getAccessibleContext().setAccessibleDescription("Register First Password Field");

        registerPass2Label.setText("Password again");
        registerContentsPanel.add(registerPass2Label);

        registerPass2Text.setText("jPasswordField1");
        registerPass2Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        registerContentsPanel.add(registerPass2Text);
        registerPass2Text.getAccessibleContext().setAccessibleName("Register Second Password Field");
        registerPass2Text.getAccessibleContext().setAccessibleDescription("Register Second Password Field");

        registerButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 4, 4));

        registerClearButton.setText("Clear");
        registerButtonsPanel.add(registerClearButton);

        registerSubmitButton.setText("Register");
        registerSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSubmitButtonActionPerformed(evt);
            }
        });
        registerButtonsPanel.add(registerSubmitButton);

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(separator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(separator4)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(registerButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addComponent(registerTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerContentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(separator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabsPanel.addTab("Register", registerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerSubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginTitleLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel loginButtonsPanel;
    private javax.swing.JButton loginClearButton;
    private javax.swing.JPanel loginContentsPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginPassLabel;
    private javax.swing.JPasswordField loginPassText;
    private javax.swing.JButton loginSubmitButton;
    private javax.swing.JPanel loginTitlePanel;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JTextField loginUserText;
    private javax.swing.JPanel registerButtonsPanel;
    private javax.swing.JButton registerClearButton;
    private javax.swing.JPanel registerContentsPanel;
    private javax.swing.JLabel registerEmail1Label;
    private javax.swing.JTextField registerEmail1Text;
    private javax.swing.JLabel registerEmail2Label;
    private javax.swing.JTextField registerEmail2Text;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel registerPass1Label;
    private javax.swing.JPasswordField registerPass1Text;
    private javax.swing.JLabel registerPass2Label;
    private javax.swing.JPasswordField registerPass2Text;
    private javax.swing.JButton registerSubmitButton;
    private javax.swing.JLabel registerTitleLabel;
    private javax.swing.JPanel registerTitlePanel;
    private javax.swing.JLabel registerUserLabel;
    private javax.swing.JTextField registerUserText;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JSeparator separator4;
    private javax.swing.JTabbedPane tabsPanel;
    // End of variables declaration//GEN-END:variables
}
